// Code generated by entc, DO NOT EDIT.

package candidate

const (
	// Label holds the string label denoting the candidate type in the database.
	Label = "candidate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"

	// EdgeSkills holds the string denoting the skills edge name in mutations.
	EdgeSkills = "skills"

	// Table holds the table name of the candidate in the database.
	Table = "candidates"
	// SkillsTable is the table the holds the skills relation/edge. The primary key declared below.
	SkillsTable = "candidate_skills"
	// SkillsInverseTable is the table name for the Skill entity.
	// It exists in this package in order to avoid circular dependency with the "skill" package.
	SkillsInverseTable = "skills"
)

// Columns holds all SQL columns for candidate fields.
var Columns = []string{
	FieldID,
	FieldTitle,
}

var (
	// SkillsPrimaryKey and SkillsColumn2 are the table columns denoting the
	// primary key for the skills relation (M2M).
	SkillsPrimaryKey = []string{"candidate_id", "skill_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
)
