// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// CandidatesColumns holds the columns for the "candidates" table.
	CandidatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Unique: true},
	}
	// CandidatesTable holds the schema information for the "candidates" table.
	CandidatesTable = &schema.Table{
		Name:        "candidates",
		Columns:     CandidatesColumns,
		PrimaryKey:  []*schema.Column{CandidatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Unique: true},
		{Name: "job_skill", Type: field.TypeInt, Nullable: true},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:       "jobs",
		Columns:    JobsColumns,
		PrimaryKey: []*schema.Column{JobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "jobs_skills_skill",
				Columns: []*schema.Column{JobsColumns[2]},

				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SkillsColumns holds the columns for the "skills" table.
	SkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// SkillsTable holds the schema information for the "skills" table.
	SkillsTable = &schema.Table{
		Name:        "skills",
		Columns:     SkillsColumns,
		PrimaryKey:  []*schema.Column{SkillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// CandidateSkillsColumns holds the columns for the "candidate_skills" table.
	CandidateSkillsColumns = []*schema.Column{
		{Name: "candidate_id", Type: field.TypeInt},
		{Name: "skill_id", Type: field.TypeInt},
	}
	// CandidateSkillsTable holds the schema information for the "candidate_skills" table.
	CandidateSkillsTable = &schema.Table{
		Name:       "candidate_skills",
		Columns:    CandidateSkillsColumns,
		PrimaryKey: []*schema.Column{CandidateSkillsColumns[0], CandidateSkillsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "candidate_skills_candidate_id",
				Columns: []*schema.Column{CandidateSkillsColumns[0]},

				RefColumns: []*schema.Column{CandidatesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "candidate_skills_skill_id",
				Columns: []*schema.Column{CandidateSkillsColumns[1]},

				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CandidatesTable,
		JobsTable,
		SkillsTable,
		CandidateSkillsTable,
	}
)

func init() {
	JobsTable.ForeignKeys[0].RefTable = SkillsTable
	CandidateSkillsTable.ForeignKeys[0].RefTable = CandidatesTable
	CandidateSkillsTable.ForeignKeys[1].RefTable = SkillsTable
}
