// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/zeako/candidate-matcher/ent/candidate"
	"github.com/zeako/candidate-matcher/ent/predicate"
	"github.com/zeako/candidate-matcher/ent/skill"
)

// CandidateUpdate is the builder for updating Candidate entities.
type CandidateUpdate struct {
	config
	hooks    []Hook
	mutation *CandidateMutation
}

// Where adds a new predicate for the builder.
func (cu *CandidateUpdate) Where(ps ...predicate.Candidate) *CandidateUpdate {
	cu.mutation.predicates = append(cu.mutation.predicates, ps...)
	return cu
}

// SetTitle sets the title field.
func (cu *CandidateUpdate) SetTitle(s string) *CandidateUpdate {
	cu.mutation.SetTitle(s)
	return cu
}

// AddSkillIDs adds the skills edge to Skill by ids.
func (cu *CandidateUpdate) AddSkillIDs(ids ...int) *CandidateUpdate {
	cu.mutation.AddSkillIDs(ids...)
	return cu
}

// AddSkills adds the skills edges to Skill.
func (cu *CandidateUpdate) AddSkills(s ...*Skill) *CandidateUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cu.AddSkillIDs(ids...)
}

// Mutation returns the CandidateMutation object of the builder.
func (cu *CandidateUpdate) Mutation() *CandidateMutation {
	return cu.mutation
}

// ClearSkills clears all "skills" edges to type Skill.
func (cu *CandidateUpdate) ClearSkills() *CandidateUpdate {
	cu.mutation.ClearSkills()
	return cu
}

// RemoveSkillIDs removes the skills edge to Skill by ids.
func (cu *CandidateUpdate) RemoveSkillIDs(ids ...int) *CandidateUpdate {
	cu.mutation.RemoveSkillIDs(ids...)
	return cu
}

// RemoveSkills removes skills edges to Skill.
func (cu *CandidateUpdate) RemoveSkills(s ...*Skill) *CandidateUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cu.RemoveSkillIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (cu *CandidateUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		if err = cu.check(); err != nil {
			return 0, err
		}
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CandidateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cu.check(); err != nil {
				return 0, err
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CandidateUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CandidateUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CandidateUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CandidateUpdate) check() error {
	if v, ok := cu.mutation.Title(); ok {
		if err := candidate.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf("ent: validator failed for field \"title\": %w", err)}
		}
	}
	return nil
}

func (cu *CandidateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   candidate.Table,
			Columns: candidate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: candidate.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: candidate.FieldTitle,
		})
	}
	if cu.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   candidate.SkillsTable,
			Columns: candidate.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: skill.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedSkillsIDs(); len(nodes) > 0 && !cu.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   candidate.SkillsTable,
			Columns: candidate.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: skill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   candidate.SkillsTable,
			Columns: candidate.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: skill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{candidate.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// CandidateUpdateOne is the builder for updating a single Candidate entity.
type CandidateUpdateOne struct {
	config
	hooks    []Hook
	mutation *CandidateMutation
}

// SetTitle sets the title field.
func (cuo *CandidateUpdateOne) SetTitle(s string) *CandidateUpdateOne {
	cuo.mutation.SetTitle(s)
	return cuo
}

// AddSkillIDs adds the skills edge to Skill by ids.
func (cuo *CandidateUpdateOne) AddSkillIDs(ids ...int) *CandidateUpdateOne {
	cuo.mutation.AddSkillIDs(ids...)
	return cuo
}

// AddSkills adds the skills edges to Skill.
func (cuo *CandidateUpdateOne) AddSkills(s ...*Skill) *CandidateUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cuo.AddSkillIDs(ids...)
}

// Mutation returns the CandidateMutation object of the builder.
func (cuo *CandidateUpdateOne) Mutation() *CandidateMutation {
	return cuo.mutation
}

// ClearSkills clears all "skills" edges to type Skill.
func (cuo *CandidateUpdateOne) ClearSkills() *CandidateUpdateOne {
	cuo.mutation.ClearSkills()
	return cuo
}

// RemoveSkillIDs removes the skills edge to Skill by ids.
func (cuo *CandidateUpdateOne) RemoveSkillIDs(ids ...int) *CandidateUpdateOne {
	cuo.mutation.RemoveSkillIDs(ids...)
	return cuo
}

// RemoveSkills removes skills edges to Skill.
func (cuo *CandidateUpdateOne) RemoveSkills(s ...*Skill) *CandidateUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cuo.RemoveSkillIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (cuo *CandidateUpdateOne) Save(ctx context.Context) (*Candidate, error) {
	var (
		err  error
		node *Candidate
	)
	if len(cuo.hooks) == 0 {
		if err = cuo.check(); err != nil {
			return nil, err
		}
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CandidateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cuo.check(); err != nil {
				return nil, err
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CandidateUpdateOne) SaveX(ctx context.Context) *Candidate {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CandidateUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CandidateUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CandidateUpdateOne) check() error {
	if v, ok := cuo.mutation.Title(); ok {
		if err := candidate.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf("ent: validator failed for field \"title\": %w", err)}
		}
	}
	return nil
}

func (cuo *CandidateUpdateOne) sqlSave(ctx context.Context) (_node *Candidate, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   candidate.Table,
			Columns: candidate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: candidate.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Candidate.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := cuo.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: candidate.FieldTitle,
		})
	}
	if cuo.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   candidate.SkillsTable,
			Columns: candidate.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: skill.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedSkillsIDs(); len(nodes) > 0 && !cuo.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   candidate.SkillsTable,
			Columns: candidate.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: skill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   candidate.SkillsTable,
			Columns: candidate.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: skill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Candidate{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues()
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{candidate.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
