// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/zeako/candidate-matcher/ent/candidate"
	"github.com/zeako/candidate-matcher/ent/skill"
)

// CandidateCreate is the builder for creating a Candidate entity.
type CandidateCreate struct {
	config
	mutation *CandidateMutation
	hooks    []Hook
}

// SetTitle sets the title field.
func (cc *CandidateCreate) SetTitle(s string) *CandidateCreate {
	cc.mutation.SetTitle(s)
	return cc
}

// AddSkillIDs adds the skills edge to Skill by ids.
func (cc *CandidateCreate) AddSkillIDs(ids ...int) *CandidateCreate {
	cc.mutation.AddSkillIDs(ids...)
	return cc
}

// AddSkills adds the skills edges to Skill.
func (cc *CandidateCreate) AddSkills(s ...*Skill) *CandidateCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cc.AddSkillIDs(ids...)
}

// Mutation returns the CandidateMutation object of the builder.
func (cc *CandidateCreate) Mutation() *CandidateMutation {
	return cc.mutation
}

// Save creates the Candidate in the database.
func (cc *CandidateCreate) Save(ctx context.Context) (*Candidate, error) {
	var (
		err  error
		node *Candidate
	)
	if len(cc.hooks) == 0 {
		if err = cc.check(); err != nil {
			return nil, err
		}
		node, err = cc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CandidateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cc.check(); err != nil {
				return nil, err
			}
			cc.mutation = mutation
			node, err = cc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cc.hooks) - 1; i >= 0; i-- {
			mut = cc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CandidateCreate) SaveX(ctx context.Context) *Candidate {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (cc *CandidateCreate) check() error {
	if _, ok := cc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New("ent: missing required field \"title\"")}
	}
	if v, ok := cc.mutation.Title(); ok {
		if err := candidate.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf("ent: validator failed for field \"title\": %w", err)}
		}
	}
	return nil
}

func (cc *CandidateCreate) sqlSave(ctx context.Context) (*Candidate, error) {
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (cc *CandidateCreate) createSpec() (*Candidate, *sqlgraph.CreateSpec) {
	var (
		_node = &Candidate{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: candidate.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: candidate.FieldID,
			},
		}
	)
	if value, ok := cc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: candidate.FieldTitle,
		})
		_node.Title = value
	}
	if nodes := cc.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   candidate.SkillsTable,
			Columns: candidate.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: skill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CandidateCreateBulk is the builder for creating a bulk of Candidate entities.
type CandidateCreateBulk struct {
	config
	builders []*CandidateCreate
}

// Save creates the Candidate entities in the database.
func (ccb *CandidateCreateBulk) Save(ctx context.Context) ([]*Candidate, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Candidate, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CandidateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (ccb *CandidateCreateBulk) SaveX(ctx context.Context) []*Candidate {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
