// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/zeako/candidate-matcher/ent/candidate"
	"github.com/zeako/candidate-matcher/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	candidateFields := schema.Candidate{}.Fields()
	_ = candidateFields
	// candidateDescTitle is the schema descriptor for title field.
	candidateDescTitle := candidateFields[0].Descriptor()
	// candidate.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	candidate.TitleValidator = candidateDescTitle.Validators[0].(func(string) error)
}
