// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Candidate is the predicate function for candidate builders.
type Candidate func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)
